const express = require("express");
const router = express.Router();
const products = require("../../controllers/products.controller");
router.post("/addproduct", products.UpImage, products.createProduct);
router.get("/getProductsbyID/:id", products.getProductsbyID);
router.get("/getAllProducts", products.getAllProducts);
router.post("/searchProducts", products.searchProducts);
router.post("/getAllProductsbyCat", products.getAllProductsbyCat);
router.put("/:id", products.UpImage, products.updateProduct);
router.delete("/:id", products.deleteProduct);
router.post("/viewsProduct/:id", products.viewsProduct);
module.exports = router;
